Update hardhat guide
lukso-network/lukso-playground pull request #32
Opened 2024-02-06 18:07 UTC by fhildeb

2024-02-07 09:13 UTC, Hugoo commented on smart-contracts-hardhat/README.md
> +> **INFO** Make sure to add the private key of an EOA and Universal Profile address for deployment.
I would reco to remove the "Universal Profile address" part.

A new user will not have this info avail. yet and this might block them in going further. Moreover, this is not needed for the first tutorials. I suggest to add this "Universal Profile address" where the tutorial requires it and not as a "global dependency" let's say

2024-02-07 09:14 UTC, Hugoo commented on smart-contracts-hardhat/README.md
>  npm i
npm or bun ?

I see a bun lock file

Is this folder using bun or npm?

If bun let's use bun cli for the scripts

2024-02-07 09:16 UTC, Hugoo reviewed
can you reduce the text by 50% maybe?

i think this README is turning into a Docs guide - which is good, but... we might need a bit less in there.

2024-02-07 09:17 UTC, Hugoo commented on smart-contracts-hardhat/README.md
> +The syntax of smart contracts works by **inheritance**, similarly as Object Oriented Programming language. Every object represents an individual smart contracts, which inherits underlying functionali
> The syntax of smart contracts works by **inheritance**, similarly as Object Oriented Programming language. Every object represents an individual smart contracts, which inherits underlying functionalities.

this is not needed

2024-02-07 13:26 UTC, CJ42 requested changes

2024-02-07 13:26 UTC, CJ42 commented on smart-contracts-hardhat/contracts/NFT-Dynamics/DynamicNFTMetadataContract.sol
> +    bytes32 constant _LSP8_REFERENCE_CONTRACT =
This data key is actually available from the smart contract package to be imported.

```solidity
import {
    _LSP8_REFERENCE_CONTRACT_KEY
} from "@lukso/lsp-smart-contracts/contracts/LSP8IdentifiableDigitalAsset/LSP8Constants.sol";
```

2024-02-07 13:26 UTC, CJ42 commented on smart-contracts-hardhat/package.json
> +    "@nomiclabs/hardhat-ethers": "npm:hardhat-deploy-ethers@^0.4.1",
what is this dependency? This seems incorrect to me

2024-02-07 13:26 UTC, CJ42 commented on smart-contracts-hardhat/package.json
> +    "@nomiclabs/hardhat-ethers": "npm:hardhat-deploy-ethers@^0.4.1",
Since hardhat toolbox is installed, it already contains `hardhat-ethers` inside. See Hardhat docs

https://hardhat.org/hardhat-runner/plugins/nomicfoundation-hardhat-toolbox

![Uploading image.png…]()

2024-02-07 13:26 UTC, CJ42 commented on smart-contracts-hardhat/package.json
>      "prettier-plugin-solidity": "^1.3.1"
Let's update this one to latest as well

2024-02-07 13:26 UTC, CJ42 commented on smart-contracts-hardhat/README.md
> +# Basic Sample Hardhat Project
Suggest giving it a more specific title maybe? This is what I had in my repo + it's the default when you bootstrap a Hardhat project, but it sounds very generic for the LUKS Playground.

@Hugoo @fhildeb ideas?

2024-02-07 13:26 UTC, CJ42 commented on smart-contracts-hardhat/README.md
> +This project is used as a guide to show how to setup HardHat to work with the **[LUKSO networks](https://docs.lukso.tech/networks/mainnet/parameters)** and **[LSPs](https://docs.lukso.tech/contracts/
```suggestion
This project is used as a guide to show how to setup HardHat to interact with **[LSPs](https://docs.lukso.tech/contracts/introduction)** smart contracts on **[LUKSO networks](https://docs.lukso.tech/networks/mainnet/parameters)**.
```

2024-02-07 13:26 UTC, CJ42 commented on smart-contracts-hardhat/README.md
> +[HardHat](https://hardhat.org/docs) is a development environment to:
I would delete completely this section + bullet points. This LUKSO Playground is intended to focus on LUKSO tools usage, not to explain what Hardhat is.
People coming into this repo should already know what Hardhat is and how to use it. If they don't they could go the Hardhat docs to learn these.

2024-02-07 13:26 UTC, CJ42 commented
Also suggest removing `--force` param in the command. So it's caches the build

<img width="490" alt="image" src="https://github.com/lukso-network/lukso-playground/assets/31145285/6b7f875e-14dd-420d-87d2-d1a3561afc74">

2024-02-08 14:43 UTC, CJ42 approved these changes

2024-02-08 14:49 UTC, merged