Sync playground with docs
lukso-network/lukso-playground pull request #41
Opened 2024-02-16 15:17 UTC by fhildeb

2024-02-16 16:55 UTC, b00ste commented on digital-assets/fetch-tokenid-metadata.ts
> +const isLSP8 = await myAsset.supportsInterface(INTERFACE_IDS.LSP8IdentifiableDigitalAsset);
mention that is should be version `v0.14.0` of `@lukso/lsp-smart-contracts`

2024-02-16 16:55 UTC, b00ste commented on digital-assets/fetch-tokenid-metadata.ts
> +  const fileUrl = tokenBaseURI + contentID;
Here you also need to append the token id based on [LSP8TokenIdFormat](https://github.com/lukso-network/LIPs/blob/main/LSPs/LSP-8-IdentifiableDigitalAsset.md#lsp8tokenidformat)

2024-02-22 15:53 UTC, Hugoo commented
Somehow this was not merged on time and it has conflicts now.

Can you fix them so we can merge?

2024-02-22 16:13 UTC, fhildeb commented
I removed token ID fetches from this- so it stays getDataForTokenID only. I will open another file for `baseURI` and `tokenIDFormat`

LGTM

2024-02-22 16:18 UTC, Hugoo commented on digital-assets/fetch-tokenid-metadata.ts
> +  }
If the address set it not a contract it will fail

```ts
let isLSP8: false;

try {
 isLSP8 = await myAssetContract.supportsInterface(
    INTERFACE_IDS.LSP8IdentifiableDigitalAsset,
  );
} catch(err) {
 console.error('Could not check if address XXX supports interface YYY, is it a smart contract address?');
 return;
}

if (!isLSP8) {
    console.log('Contract: ${address....} does not support the LSP8.... interface ID....');
    return;
  }
```


smtgh like that

2024-02-22 16:19 UTC, Hugoo commented on digital-assets/fetch-tokenid-metadata.ts
> +  }
It may add some code but if ppl copy/paste these snippets all around, we better show how to try catch as the contract call can very likely fail (if the address provided is not a contract, does not have that function etc. We need to show the right way)

2024-02-23 09:27 UTC, Hugoo commented on digital-assets/fetch-tokenid-metadata.ts
> +    console.log('Contract is not an LSP8 asset');
Please add address in the erorr log:

cf:

```
console.error('Could not check if address XXX supports interface YYY, is it a smart contract address?');
 return;
}

if (!isLSP8) {
    console.log('Contract: ${address....} does not support the LSP8.... interface ID....');
    return;
```

Replace XXX with address
and YYY with interface ID
etc.

https://github.com/lukso-network/lukso-playground/pull/41#discussion_r1499515014

2024-03-04 18:30 UTC, CJ42 requested changes
added review comments

2024-03-04 18:30 UTC, CJ42 commented on digital-assets/fetch-tokenid-metadata.ts
> +    // https://docs.lukso.tech/contracts/contracts/ERC725/#supportsinterface
Suggest not putting a link to our docs here. SupportInterface calls (ERC165) is something very common and well known in the web3 developer community. They will understand what it is.

2024-03-04 18:30 UTC, CJ42 commented on digital-assets/fetch-tokenid-metadata.ts
> +    return `https://api.universalprofile.cloud/ipfs/${link.slice(7)}`;
suggest adding variable above:

```js
const ipfsHash = link.slice(7)
```

2024-03-04 18:30 UTC, CJ42 commented on digital-assets/fetch-tokenid-metadata.ts
> +    // Use your default IPFS Gateway address
I think the comment is incorrect. If this is HTTP, you don't use an IPFS Gateway at all. You just fetch directly from the internet.

2024-03-05 10:26 UTC, fhildeb commented
Thanks for the review! Applied suggestions

2024-03-14 14:24 UTC, b00ste approved these changes

2024-03-19 14:49 UTC, CJ42 approved these changes

2024-03-19 14:49 UTC, merged